### ISSUE TITLE
MIMIC III BENCHMARKs mapping between  

### ISSUE THREAD

**Issue by kara4141** [BoulderDS/value-of-medical-notes#4]
Hi!

Thanks for this wholesome work! I am doing similar things with predicting LOS adding text information based on MIMIC3 BENCHMARK. As MIMIC3 BENCHMARK partition and group the data into episodes of csv. It kinda lost track of the source admission id and such from my understanding. I am wondering whether you guys figured out how to map the episodes with the source data (such as admission id).

Thanks and hope you are staying well and safe!

**Comment by joe32140** [comment]
Hi! 

If you have the MIMIC-III dataset, you can run our first script `mimic3preprocess.scripts.extract_subjects` to get the mapping between patient id and admission id, i.e., `HADM_ID`  in `all_admissions.csv` file. 

Feel free to let me know if you have any questions!

**Comment by kara4141** [comment]
Thanks for the fast response !

That mapping is really helpful, but I am more concern of the mapping from `episode `, generated by the mimic3benchmark if you recall how they seprate the data into many csv files, to `HADM_ID`.

Thanks!

**Comment by joe32140** [comment]
I see! The episode number is actually the order of admission of each patient as shown in 
https://github.com/BoulderDS/value-of-medical-notes/blob/cb6aa5e353366176a840467e00b592c725533a96/mimic3preprocess/scripts/extract_episodes_from_subjects.py#L63-L81

For example, 
```
SUBJECT_ID, HADM_ID
22, 50
22, 66
```
HADM_ID 50 will be `22_episode1_timeseries.csv` and HADM_ID 66 will be `22_episode2_timeseries.csv`.

**Comment by kara4141** [comment]
Terrific!

So I am assuming the first number (22) among `22_episode1_timeseries.csv` is the subject id?

**Comment by joe32140** [comment]
Exactly!
